[project]
name = "sistemasolarrafaela"
version = "0.1.0"
description = "Web del sistema solar a escala de Rafaela"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "jinja2>=3.1.6",
    "natsort>=8.4.0",
]
